- name: Installing Nginx server
  hosts: web
  tasks:
    - name: Latest Nginx version installed
      ansible.builtin.apt:
        name: nginx
        state: latest
    - name: Ensure Nginx is enabled and running
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: started
    - name: Copy Nginx configuration file
      copy:
        src: nginx/status.conf
        dest: /etc/nginx/conf.d/status.conf
      notify:
          - restart_nginx
